"""Initial migration

Revision ID: 5fa46421eb39
Revises: 
Create Date: 2025-11-27 14:09:26.717258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa46421eb39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capacity_estimated', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plate', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('car', 'motorcycle', 'bicycle', 'truck', 'other', name='vehicletype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('parking_zones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parking_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parking_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.Enum('car', 'motorcycle', 'bicycle', 'truck', 'other', name='vehicletype'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parking_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=True),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('active', 'exited', 'cancelled', name='registrationstate'), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('parking_id', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state', sa.Enum('pending', 'paid', 'void', name='invoicestate'), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'mobile', 'transfer', 'other', name='paymentmethod'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('registrations')
    op.drop_table('cells')
    op.drop_table('user_roles')
    op.drop_table('parking_zones')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('parkings')
    # ### end Alembic commands ###
